apiVersion: v1
kind: Service
metadata:
  name: mfront-service
spec:
  ports:
    - port: 50
      targetPort: 8520
  selector:
    app: mfront

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfront-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mfront
  template:
    metadata:
      labels:
        app: mfront
    spec:
      containers:
        - name: mfront-container
          image: blamyae/mfront:1.0.0
          ports:
            - containerPort: 8520
