apiVersion: v1
kind: ConfigMap
metadata:
    name: mongodb-conf
data:
    host: localhost
    dbname: mcommerceDB
    authSource: admin
---
apiVersion: v1
kind: Service
metadata:
    name: back_mcommande
spec:
    selector:
    app: backend
    ports:
    - port: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: back-mcommande-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
            - name: backend
              image: blamyae/mcommande:1.0.0
              ports:
                 - containerPort: 8081
                   name: backend-port
              livenessProbe:
                httpGet:
                    port: backend-port
                    path: /health
                failureThreshold: 1
                periodSeconds: 10
              startupProbe:
                httpGet:
                    port: backend-port
                    path: /health
                failureThreshold: 30
                periodSeconds: 10
              readinessProbe:
                httpGet:
                    port: backend-port
                    path: /ready
                failureThreshold: 1
                periodSeconds: 10
              env:
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                        name: mongodb-conf
                        key: host
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                        name: mongodb-conf
                        key: dbname
                - name: AUTH_SOURCE
                  valueFrom:
                    configMapKeyRef:
                        name: mongodb-conf
                        key: authSource
                - name: MONGO_USERNAME
                  valueFrom:
                    secretKeyRef:
                        name: mongodb-secret
                        key: username
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        name: mongodb-secret
                        key: password
